applications:
    # The name of this app. Must be unique within a project.
    cs:
        # Where the app is located on the filesystem.
        source:
            root: "cs"

        # The runtime the application uses.
        stack: ["crowdsec"]

        # Configuration of the build of the application.
        build:
            flavor: none

        # Hooks into the build and deploy stages.
        hooks:
            deploy: |
                set -e
                bash scripts/deploy.sh