applications:
    # The name of this app. Must be unique within a project.
    crowdsec:
        # Where the app is located on the filesystem.
        source:
            root: "crowdsec"
        # The runtime the application uses.
        stack: ["gettext"]
        # Configuration of the build of the application.
        build:
            flavor: none

        # Need more RAM than CPU #TODO Select one ?
        #container_profile: BALANCED

        mounts:
            'crowdsec':
                source: instance
                source_path: 'etc/crowdsec'
            'crowdsec_data':
                source: instance
                source_path: 'var/lib/crowdsec/data'
            'logpit':
                source: storage
                source_path: 'var/log'

        hooks:
            build: |
                set -eu
                ./scripts/systemd_install.sh
            deploy: |
                set -eu
                .scripts/deploy_crowdsec.sh
        

        # Hooks into the build and deploy stages.
        hooks:
            deploy: |
                set -e
                bash scripts/deploy.sh