applications:
    # The name of this app. Must be unique within a project.
    crowdsec:
        # Where the app is located on the filesystem.
        source:
            root: "crowdsec"
        # The runtime the application uses.
        stack: ["gettext"]
        # Configuration of the build of the application.
        build:
            flavor: none

        # Need more RAM than CPU #TODO Select one ?
        #container_profile: BALANCED

        mounts:
            'etc':
                source: instance
                source_path: 'etc'
            'var':
                source: instance
                source_path: 'var'
            'logpit':
                source: storage
                source_path: 'logpit'

        hooks:
            build: |
                set -eu
                ./scripts/systemd_install.sh
            deploy: |
                set -eu
                ./scripts/deploy_crowdsec.sh
        
        workers:
            service_crowdsec:
                commands:
                start: |
                    ./scripts/start-crowdsec-service.sh

