# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
  - cron:  '0 4 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "bxuild"
  backup:
    name: Perform Backup
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2.2.0
      - name: Install Upsun CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/platformsh/cli/main/installer.sh | VENDOR=upsun bash
          echo "/home/runner/.upsun/bin" >> $GITHUB_PATH
      - name: Run backup
        run: upsun backup:create -W -p ${{secrets.UPSUN_PROJECT}} main
        env:
          UPSUN_CLI_TOKEN: ${{secrets.UPSUN_CLI_TOKEN}}
